- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/psf/black
  rev: 21.11b1
  hooks:
    - id: black
      language_version: python3.10
